- LICENSE
- README.md
- pom.xml
- securebanking-openbanking-uk-rcs-api/README.md
- securebanking-openbanking-uk-rcs-api/pom.xml
- securebanking-openbanking-uk-rcs-app/README.md
- securebanking-openbanking-uk-rcs-app/pom.xml
- securebanking-openbanking-uk-rcs-server/README.md
- securebanking-openbanking-uk-rcs-server/docker-compose.yml
- securebanking-openbanking-uk-rcs-server/pom.xml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/RcsApplication.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/DataConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/SwaggerDocumentationConfig.java
- securebanking-openbanking-uk-rcs-server/src/main/resources/application.yml
- securebanking-openbanking-uk-rcs-server/src/main/resources/messages/swagger.properties
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/RcsApplicationTest.java
- Contains initial modules
- Includes a placeholder rcs-app module
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/38
> 38 - Initial skeleton project for the RCS

- pom.xml
- securebanking-openbanking-uk-rcs-api/pom.xml
- securebanking-openbanking-uk-rcs-app/pom.xml
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/38
> 38 - POM fixes

- .github/workflows/merge-master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Add basic Github actions for merge, pr and the release of jars.
> add actions for merge, pr and release

- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApi.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/FilePaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiController.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/am/UserProfileService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRConsentStatusCode.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRDomesticPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRFilePaymentConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRFilePaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRFundsConfirmationConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRFundsConfirmationConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticPaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticStandingOrderConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/FilePaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/FundsConfirmationConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/PaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/ConsentDetailsRequestTestDataFactory.java
Issue: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66
> 66: Add File payments and funds confirmation consents

- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalStandingOrderConsentDetails.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalPaymentConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalScheduledPaymentConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalScheduledPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalStandingOrderConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalStandingOrderConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalPaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalScheduledPaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalStandingOrderConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalPaymentConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalScheduledPaymentConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/InternationalStandingOrderConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalPaymentConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalPaymentConsentTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalScheduledPaymentConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalScheduledPaymentConsentTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalStandingOrderConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalStandingOrderConsentTestDataFactory.java
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66
> 66: Add retrieval of international payment consents

- securebanking-openbanking-uk-rcs-sample/docker/Dockerfile
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose.yml
- securebanking-openbanking-uk-rcs-sample/docker/scripts/wait-for.sh
- securebanking-openbanking-uk-rcs-sample/pom.xml
- securebanking-openbanking-uk-rcs-server/pom.xml
- Ensure config server is ready before starting spring boot application
- Default image tag to latest for local builds
- Move Dockerfile to docker folder
- Tidy up pom - remove unnecessary properties
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/14
> 14 - docker-compose: Wait for config. Tidy docker setup

- securebanking-openbanking-uk-rcs-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRDomesticPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRDomesticScheduledPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRDomesticStandingOrderConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalScheduledPaymentConsentData.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRInternationalStandingOrderConsentData.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRDomesticScheduledPaymentConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRDomesticStandingOrderConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalScheduledPaymentConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRInternationalStandingOrderConsentDataTestDataFactory.java
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/76
> 76: v3.1.8 Read/Write API changes, excluding VRPs

- .gitignore
- .idea/.gitignore
- .idea/runConfigurations/rcs_service.xml
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApi.java
- securebanking-openbanking-uk-rcs-sample/README.md
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rcs-sample/docker/run-docker-compose-git.sh
- securebanking-openbanking-uk-rcs-sample/docker/wiremock/__files/idm-get-account-consent-response.json
- securebanking-openbanking-uk-rcs-sample/docker/wiremock/mappings/idm-get-account-consent-request.json
- securebanking-openbanking-uk-rcs-sample/docker/wiremock/mappings/idm-update-account-consent-request.json
- securebanking-openbanking-uk-rcs-sample/src/main/resources/application.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiController.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/AccountConsentService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRAccountAccessConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRAccountConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/common/RcsConstants.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/AccountAccessConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/AccountConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/AccountAccessConsentDecisionServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/AccountConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRAccountAccessConsentTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
- Changes and fixes to get the ConsentDetails
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/44
> 44: Securebanking user interfaces - RCS UI

- .github/workflows/pr.yml
- .gitignore
- Makefile
Run functional tests through the pr action.
Reorganise to flow the same was as rs and ig
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
> run functional tests on actions pr

- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-sample/docker/wiremock/mappings/jwkms-sign-claims-request.json
- securebanking-openbanking-uk-rcs-sample/src/test/resources/application-test.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionResponseHandler.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/jwkms/JwkmsApiClient.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/TestInitializer.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/WireMockStubHelper.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
Resolves: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/88
> 88: Sign Consent Response via IG

- .github/workflows/merge.yml
implement git sha short version as a reusable environment variable
issue: SecureBankingAccessToolkit/SecureBankingAccessToolkit#89
> implement short git sha

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
- pom.xml
- securebanking-forgerock-cloud-client/pom.xml
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/configuration/ConfigurationPropertiesClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/AccountConsentService.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/ApiClientServiceClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/JwkServiceClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/UserServiceClient.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/configuration/ConfigurationPropertiesClientTest.java
- securebanking-forgerock-cloud-client/src/test/resources/application-test.yml
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-server/pom.xml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/rs/AccountService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/FilterConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsApplicationConfiguration.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationPropertiesTest.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
- Delete unused properties spring config
- Added env properties to helm chart
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/95
> 95: environment specific values

- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/Constants.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/models/AccountConsentDecisionTest.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/ConsentDecisionTestDataFactory.java
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiController.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- Fix consent decision status from 'Approved' to 'Authorised'
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/103
> 103: Consent decision status fix

- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- Fix local spring configuration.
> Fix spring configuration for local environment

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- Added steps actions to deploy the artifact package before build an Image
Issue:https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/106
> 106: improve action when merge

- pom.xml
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/IntentType.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/ConsentServiceClient.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticStandingOrderConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/FilePaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiController.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/util/AccountWithBalanceMatcher.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/AccountWithBalanceMatcherTest.java
- Bumped refactorised openbanking-uk-bom
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/219
> 219: vrp payment consent decisions

- .github/workflows/merge.yml
- .github/workflows/pr.yml
See issue; https://github.com/google-github-actions/setup-gcloud/issues/539
> Pin setup-gcloud github actions to v0 rather than master

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/configuration/ConfigurationPropertiesClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/AccountConsentService.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/ApiClientServiceClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/JwkServiceClient.java
- securebanking-forgerock-cloud-client/src/main/java/com/forgerock/securebanking/platform/client/services/UserServiceClient.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/configuration/ConfigurationPropertiesClientTest.java
- securebanking-forgerock-cloud-client/src/test/resources/application-test.yml
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/rs/AccountService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationProperties.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationPropertiesTest.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
- Updated the deployment template with env values from configMap `platform-config`
- Update the github actions to use the correct version of gcloud configuration environment
- Updated properties names to normalize them
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/229
> 229: cdk-cdm-fidc same configuration

- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticPaymentsConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticStandingOrderConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/Constants.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/327
> 327: Domestic standing order consent Decision submit

- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/Constants.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/363
> 363: International payment consent decision 

- README.md
- pom.xml
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApi.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApi.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/swagger/SwaggerApiTags.java
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rs-docker.yml
- securebanking-openbanking-uk-rcs-sample/src/main/resources/application.yml
- securebanking-openbanking-uk-rcs-sample/src/main/resources/messages/swagger.properties
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/swagger/SwaggerConfiguration.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/swagger/SwaggerConfigurationTest.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
- Swagger documentation improvements
- Updated cors filter
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/319
> 319: restful api swagger documentation

- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalPaymentConsentDetails.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/420
> 420: JsonNull exception when mapping International Payment

- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalScheduledPaymentConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/general/ConsentDetailsBuilderFactory.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/404
> 404: International scheduled payment consent details

- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/Constants.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/405
> 405: International Scheduled  Payment consent decision

- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticScheduledPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticStandingOrderConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalScheduledPaymentConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/AccountsConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/DomesticStandingOrderConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalScheduledPaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalStandingOrderConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticScheduledPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticStandingOrderConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/AccountConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/ConsentDetailsBuilderFactoryTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticScheduledPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticStandingOrderConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/457
> 457: Send the ExchangeRateInformation from Data to rcs-ui. Calculate Charges

- Dockerfile
- securebanking-openbanking-uk-rcs-sample/docker/Dockerfile
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/508
> 508: Use base image gcr.io/forgerock-io/java-17:latest

- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalStandingOrderConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/InternationalStandingOrderConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalStandingOrderConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/general/ConsentDetailsBuilderFactory.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalStandingOrderConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/464
Adding support for international standing order consent details
> 464: International Standing Order Consent Details

- pom.xml
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/FilePaymentConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/FilePaymentConsentDetails.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/FilePaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/general/ConsentDetailsBuilderFactory.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/FilePaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/550
Description: Adding file payment consent details.
> 550: file payment consent details

- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/Constants.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/551
Description: Added support for file payment consent decision.
> 551: Adding file payment consent decision

- secure-api-gateway-ob-uk-rcs-sample/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/sample/RcsApplication.java
- Fix component scan
Issue: https://github.com/secureapigateway/secureapigateway/issues/835
> 835: rename repository

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
Removing dependency on spring config server and its configuration.
Merging config from: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-spring-config/blob/master/docker/securebanking-openbanking-uk-rcs.yml into secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/881
> 881: Moving spring config from the config server repo into the app

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
https://github.com/SecureApiGateway/SecureApiGateway/issues/749
> 749: Fixing CONSENT_REPO_URI env var

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/slackNotification.yml
- .gitignore
- Makefile
- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Changes to make ready to build a release artifact
- Bumped parent release 0.9.0
- bumped gateway-ob-uk-common-bom release 0.9.0
- Updated merge master workflow
- Updated pom file scm section
- Added release caller workflow
Issue:https://github.com/SecureApiGateway/SecureApiGateway/issues/812
> 812: release actions

- pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
Use latest versions suggested by dependabot
Issue: https://github.com/secureapigateway/secureapigateway/issues/929
> 929: Update gson and mockito-inline

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/secureapigateway/secureapigateway/issues/932
> 932: Update argo application name in github workflows

- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
Port 80 was declared but needs to be port 8080
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/939
> 939: Incorrect target port for service 

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/domesticstandingorder/v3_1_10/RestDomesticStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domesticscheduled/v3_1_10/CreateDomesticScheduledPaymentConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domesticstandingorder/v3_1_10/CreateDomesticStandingOrderConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domesticstandingorder/v3_1_10/DomesticStandingOrderConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/BaseConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/payment/DomesticStandingOrderConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/DomesticPaymentConsentRepository.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/DomesticScheduledPaymentConsentRepository.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/DomesticStandingOrderConsentRepository.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/account/DefaultAccountAccessConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DefaultDomesticStandingOrderConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DomesticStandingOrderConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DefaultDomesticScheduledPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DefaultDomesticStandingOrderConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/DomesticStandingOrderConsentDecisionService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/DomesticStandingOrderConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/BasePaymentConsentDecisionServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/DomesticScheduledPaymentConsentDecisionServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/DomesticStandingOrderConsentDecisionServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/ConsentDetailsApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/DomesticStandingOrderConsentDetailsServiceTest.java
Added DomesticStandingOrderEntity to the MongoDB repository, plus support in the service layer and public API.
Implemented details and decision controller logic for this payment type.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1025
> 1025: Adding Support for Domestic Standing Order Consents to RCS Consent Store

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/conent/store/client/account/v3_1_10/AccountAccessConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/account/v3_1_10/AccountAccessConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/account/v3_1_10/CreateAccountAccessConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/account/AccountAccessConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/account/DefaultAccountAccessConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/account/AccountAccessConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentDecisionApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/account/AccountAccessConsentDetailsServiceTest.java
Updating AccountAccessConsentEntity to store FRReadConsent
https://github.com/SecureApiGateway/SecureApiGateway/issues/1023
> 1023: Changing AccountAccessConsent to store FR data model type

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1035
> 1035: Enabling Account Access Consent Store

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1050
> 1050: Enabling Domestic VRP Consents to use the RCS Consent Store

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1060
> 1060: Enabling Domestic Scheduled Payment Consents in the Consent Store

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/datamodel/funds/v3_1_10/FundsConfirmationConsent.java
- Added authorised debtor account support to be stored in the consent
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1093
> 1093: funds confirmation availability debtor account support

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- Upgrade chart version to 2.0.0
- Rollback release created commit
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
> 1099: rollback release created to update chart version

- pom.xml
- Bumped commons release 2.0.3
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1128
> 1128: prepare release patch 2.0.2

- .github/workflows/merge.yml
Didn't remove prefix for docker image repo
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987
> 987: Artifact Registry Migration

- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1220
> 1220: Fix workflow for dependabot

- pom.xml
Updating to the latest SNAPSHOT versions of parent and common dependencies
https://github.com/SecureApiGateway/SecureApiGateway/issues/1223
> 1223: Updating parent and common dependencies

- .github/workflows/merge.yml
- .github/workflows/pr.yml
https://github.com/SecureApiGateway/SecureApiGateway/issues/1139
> 1139: Updating Java version to 17

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/customerinfo/v1_0/CustomerInfoConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/account/v3_1_10/AccountAccessConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/customerinfo/v1_0/CustomerInfoConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/account/DefaultAccountAccessConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/customerinfo/DefaultCustomerInfoAccessConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentDecisionApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/customerinfo/CustomerInfoConsentDetailsServiceTest.java
Accounts data model in common module has been re-generated using a newer version of the code generator, minor updates to code in the RCS to be compatible with changes to the data model.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
> 1243: Changes to be compatible with the re-generated accounts data model

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/VRPConsentStateModel.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/DefaultDomesticVRPConsentServiceTest.java
Minor changes to be compatible with the updated data models, most changes relate to the name of the status enum changing.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1243
> 1243: Changes to be compatible with the re-generated vrp data model

- .github/workflows/codeql.yml
Adding codeql.yml configuration.
Scanning will be done when a PR is merged to master and on a once weekly schedule.
https://github.com/SecureApiGateway/SecureApiGateway/issues/900
> 900: Configuring CodeQL scanning

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1257
> 1257: Update java action and distribution

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264
> 1264: Update actions that have deprecations

- _infra/helm/securebanking-openbanking-uk-rcs/readme.md
- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
Rename deployment-config to be core-deployment-config & ob-deployment-config
Change openig-secrets-env to core-secrets & ob-secrets
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1315
> 1315: Remove unwanted config from dev-core

- pom.xml
- Updating parent to 2.3.2-SNAPSHOT
- Updating common to 2.3.1-SNAPSHOT
https://github.com/SecureApiGateway/SecureApiGateway/issues/1364
> 1364: Updating parent and common dependencies

- .github/workflows/pr-helm.yml
- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Update Parent and Common version to 3.0.0 for dependancies
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404
> 1404: Create and Release SAPIG Core and OB

- Makefile
Standardise the makefile to be in line with RS
Issue: https://github.com/SecureApiGateway/secure-api-gateway-ci/pull/36
> 1434: Adjust RCS makefile

- .github/workflows/codeql.yml
- .github/workflows/merge.yml
- .github/workflows/pr-helm.yml
- .github/workflows/pr.yml
Enable manual trigger for PR and Merge workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1465
> 1465: Allow Manual run of workflows

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Update Parent, Common & Helm version to `3.1.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476
> 1476: Build and Deploy SAPIG 3.1.0 to relenv

- .github/workflows/merge.yml
- .github/workflows/pr.yml
Add in ob-v* to pr and merge trigger
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1481
> 1481: Build V4 Images

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/BaseAccountAccessConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/customerinfo/BaseCustomerInfoConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/BaseFundsConfirmationConsentApiController.java
https://github.com/SecureApiGateway/SecureApiGateway/issues/1440
> 1440: Add missing copyright headers

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/ConsentStoreApiConfiguration.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/customerinfo/v1_0/CustomerInfoConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/v4_0_0/DomesticStandingOrderConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/BaseControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/customerinfo/v1_0/CustomerInfoConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/BasePaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/PaymentConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/v3_1_10/DomesticPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/BaseDomesticStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticstandingorder/v4_0_0/DomesticStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/v3_1_10/FilePaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/international/v3_1_10/InternationalPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalscheduled/v3_1_10/InternationalScheduledPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalstandingorder/v3_1_10/InternationalStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticstandingorder/BaseRestDomesticStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticstandingorder/DomesticStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticstandingorder/v4_0_0/RestDomesticStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticstandingorder/BaseDomesticStandingOrderConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticstandingorder/v4_0_0/DomesticStandingOrderConsentStoreClientTest.java
Add Consent API controller and client impl for Domestic Standing Order Consents v4.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1504
> 1504: Add v4 Domestic Standing Order support

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Bump helm chart, parent and common to 3.2.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1516
> 1516: Create release 3.2.0 and deploy

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Merge master branch into ob-v4
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1520
> 1520: Fix Rebase Conflicts post 3.2.0 Release

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Change to use revision parameter for versioning in pom and child poms
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1543
> 1543: Upload artifacts on PR build

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/international/v4_0_0/InternationalPaymentConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/international/BaseInternationalPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/international/v4_0_0/InternationalPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalscheduled/v3_1_10/InternationalScheduledPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/BaseRestInternationalPaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/InternationalPaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/v3_1_10/RestInternationalPaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/v4_0_0/RestInternationalPaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/BaseInternationalPaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/international/v4_0_0/InternationalPaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalscheduled/v3_1_10/InternationalScheduledPaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v3_1_10/BasePaymentServiceWithExchangeRateInformationTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v3_1_10/DefaultInternationalPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v3_1_10/DefaultInternationalScheduledPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v3_1_10/DefaultInternationalStandingOrderConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v4_0_0/BasePaymentServiceWithExchangeRateInformationTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v4_0_0/DefaultInternationalPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/international/InternationalPaymentConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/international/InternationalScheduledPaymentConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/international/InternationalStandingOrderConsentDetailsServiceTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1570
> 1570: Support OBIE Read/Write API v4.0.0

- pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/v4_0_0/FilePaymentConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/BaseFilePaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/FilePaymentConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/v4_0_0/FilePaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/BaseRestFilePaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/FilePaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/v3_1_10/RestFilePaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/v4_0_0/RestFilePaymentConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/BaseFilePaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/file/v4_0_0/FilePaymentConsentStoreClientTest.java
Lob-193-file-payments-api-flow-v4
- Added consent store client for file payments.
> File Payments

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalstandingorder/v4_0_0/InternationalStandingOrderConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalstandingorder/BaseInternationalStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalstandingorder/v3_1_10/InternationalStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/internationalstandingorder/v4_0_0/InternationalStandingOrderConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/BaseRestInternationalStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/InternationalStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/v4_0_0/RestInternationalStandingOrderConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/domesticscheduled/v3_1_10/DomesticScheduledPaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/BaseInternationalStandingOrderConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/v3_1_10/InternationalStandingOrderConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/internationalstandingorder/v4_0_0/InternationalStandingOrderConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/domestic/v4_0_0/DefaultDomesticStandingOrderConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/international/v4_0_0/DefaultInternationalStandingOrderConsentServiceTest.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1594
> 1594: Support OBIE Read/Write API v4.0.0 - International Standing Orders

- .gitignore
- pom.xml
Issue may be the common using a variable
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues#workspaces/development-625027a2231bd8001f38d79f/board
> 1602: Build and Deploy SAPIG 4.0.0

- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/international/InternationalStandingOrderConsentDetailsService.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1613
Fixed frequency for international standing orders.
> Fix InternationalStandingOrderConsentDetailsService frequency

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Bump helm, parent, common & remove ${revision}
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625
> 1625: SAPIG Release 4.0.3 - Further OB V4 Support

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Revert back to revision and bump common, parent and revision to 4.0.4-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1626
> 1626: Prepare repos for Post 4.0.3

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Update revision to `4.0.4-SNAPSHOT` ready for release
Revert parent to `4.0.0`
Bump common to `4.0.4`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642
> 1642: Create SAPIG 4.0.4

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Add ${revision} back in for pr builds
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1656
> 1656: Add ${Revision} back to RCS

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/BaseDomesticVRPConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/DomesticVRPConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/vrp/BaseRestDomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/payment/vrp/DomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/datamodel/BaseCreateConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/BaseConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/ConsentService.java
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1644
> 1644: Adding PUT support

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Add revision back in
- Update parent and common to `5.0.1-SNAPSHOT`
Issue: https://github.com/SecureApiGateway/secure-api-gateway-ci/pull/180
> 1711: Post SAPIG 5.0.0 Clean Up

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Add revision back in, to be able to build PR versions of RCS for RS consumption
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322?selectedIssue=OPENIG-9650
> OpenIG-9650: SAPIG 5.0.3 Release
