- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/DomesticPaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/DomesticScheduledPaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/DomesticStandingOrderConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/PaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticPaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticScheduledPaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticStandingOrderConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/PaymentConsentDetailsService.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticPaymentConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticScheduledPaymentConsentDetailsServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/DomesticStandingOrderConsentDetailsServiceTest.java
- Reduced duplication so that there's only one implementation of `getPaymentConsent()`.
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66
> 66: Tidy up of the payment related ConsentDetailsService classes

- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/idm/dto/consent/FRPaymentConsent.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/ConsentDecisionServiceDelegate.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/FilePaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/FundsConfirmationConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/InternationalPaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/InternationalScheduledPaymentConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/InternationalStandingOrderConsentDecisionService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/ConsentDetailsServiceDelegate.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/ConsentDecisionServiceDelegateTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/decision/InternationalPaymentConsentDecisionServiceTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/service/detail/ConsentDetailsServiceDelegateTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/ConsentDetailsRequestTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/JwtHelper.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/WireMockStubHelper.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRFilePaymentConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRFilePaymentConsentTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRFundsConfirmationConsentDataTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/testsupport/idm/dto/consent/FRFundsConfirmationConsentTestDataFactory.java
- Enabled submission of all payment types
- Fixed JSON types and `ConsentDetailsServiceDelegate`
- Additional integration tests to ensure all payment types are retrieved and submitted successfully.
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66
> 66: Submission of international payment consents

- securebanking-openbanking-uk-rcs-sample/Dockerfile
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose-git.yml
- securebanking-openbanking-uk-rcs-sample/docker/docker-compose.yml
- securebanking-openbanking-uk-rcs-sample/pom.xml
Switch to spring-boot-maven-plugin, instead of jib, for docker image creation
Using SBA GCR docker registry.
**Issue**: https://github.com/SecureBankingAcceleratorToolkit/SecureBankingAcceleratorToolkit/issues/66
> 66: Switched to spring-boot-maven-plugin for docker image creation

- _infra/helm/securebanking-openbanking-uk-rcs/templates/ingress.yaml
- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
Allow the ingress to be configurable so we can set different domains/subdomains for both the host and tls cert.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs/issues/20
> make ingress configurable

- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
RCS in dev cluster was returning 502 due to the https backend annotation inside its ingress.
> fix 502 error in nginx

- _infra/helm/securebanking-openbanking-uk-rcs/templates/ingress.yaml
Dev ingress should direct traffic to the correct service whose name is taken from the chart name.
> forward to the correct service

- securebanking-openbanking-uk-rcs-sample/pom.xml
- securebanking-openbanking-uk-rcs-sample/src/main/resources/application.yml
Following the spring [actuator guide](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html). Expose the prometheus metrics endpoint.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs/issues/26
> add prometheus micrometer dependency

- _infra/helm/securebanking-openbanking-uk-rcs/templates/service.yaml
Give the port a name for use with the prometheus service monitor manifest.
Our Prometheus ServiceMonitor [manifest](https://github.com/ForgeCloud/sbat-deploy/pull/38) needs to match a service via its `app` label - add `app` label with Chart name
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs/issues/26
> add match labels and name the port

- .github/workflows/merge-master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
Add github sha to docker image on merge to master.
add github tag to docker image and push to release repo when a release is made
remove all release repo references from merge/pr actions.
Publishing a helm chart is not required at the merge or pr phase.
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
> add release, pr ad merge actions

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- _infra/helm/securebanking-openbanking-uk-rcs/values.yaml
Huge amount of CPU being requested at start up caused node issue and
eviction of pods. We need to change the way tomcat is started such
that it respects the container memory limits and has a guaranteed
quality of service.
Set the following java opts;
-XX:+UseG1GC -XX:+UseContainerSupport -XX:MaxRAMPercentage=50
Update the chart version as extension/v1beta1 is old and I was getting
warnings that is deprecated, and it simply won't deploy on newer
versions of k8s, e.g. in local minikube.
Note: These changes dramatically increase the start up time of the
RCS.This meant the pods were starting to fail as the liveness probe
wasn't responding in time. To address that I have increased the
`intitalDelaySeconds` value  on the liveness probe
Issue: …
> 311: Provide limits and JAVA_OPTS to control mem

- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/UtilConverter4Test.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/util/Constants.java
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/465
Description: Added support for international standing order consent decision.
> 465: Adding international standing order consent decision

- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/AccountAccessConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticScheduledPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/DomesticStandingOrderConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalScheduledPaymentConsentDetailsTestFactory.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/InternationalStandingOrderConsentDetailsTestFactory.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/AccountConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticScheduledPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticStandingOrderConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalStandingOrderConsentDetailsConverter.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/AccountConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/ConsentDetailsBuilderFactoryTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticScheduledPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/DomesticStandingOrderConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalScheduledPaymentConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-api/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/converters/InternationalStandingOrderConsentDetailsConverterTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiControllerTest.java
IG RepoConsent route now returns OBIntentObject in the response, previously it returned the intents Data field, updating RCS to parse the new response structure
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/522
> 522: Updating RCS to parse OBIntentObject from the IDM consent response

- .github/workflows/pr.yml
Fix for codefresh changes for allowing github actions to call pipelines
Issue : https://github.com/SecureApiGateway/SecureApiGateway/issues/706
> 706 Fix github actions calling codefresh pipelines

- pom.xml
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/services/ConsentServiceTest.java
- securebanking-forgerock-cloud-client/src/test/java/com/forgerock/securebanking/platform/client/test/support/ConsentDetailsRequestTestDataFactory.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiController.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsTestValidations.java
- Improved tests
- [securebanking-openbanking-uk-bom](https://github.com/SecureApiGateway/securebanking-openbanking-uk) version updated to 1.1.9-SNAPSHOT
- Added support to set the debtor account in the consent details instead of retrieve all user accounts Issue:https://github.com/SecureApiGateway/SecureApiGateway/issues/731
> 731: optional debtor account payment initiation

- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApi.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApi.java
- securebanking-openbanking-uk-rcs-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/api/dto/consent/details/ConsentDetails.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDecisionApiControllerTest.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/api/ConsentDetailsApiControllerTest.java
Using request path prefix /rcs/api to make this consistent with other ingress paths.
This will produce cleaner ingress and IG configuration when we run this component behind IG.
- /rcs/api will go to the backend
- /rcs/ui will go to the frontend
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805
> 805: Changing request path prefix from /api/rcs to /rcs/api

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- securebanking-openbanking-uk-rcs-sample/docker/config/securebanking-openbanking-uk-rcs-docker.yml
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/rs/AccountService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/client/rs/DomesticPaymentService.java
- securebanking-openbanking-uk-rcs-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RsConfiguration.java
- securebanking-openbanking-uk-rcs-server/src/test/java/com/forgerock/securebanking/openbanking/uk/rcs/configuration/RcsConfigurationPropertiesTest.java
- securebanking-openbanking-uk-rcs-server/src/test/resources/application-test.yml
Configuring RS address via new spring config: `rs.baseUri: http://${rs.internal.svc}:8080`
This uses the RS_INTERNAL_SVC environment variable (as provided by the config map).
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/816
> 816: Configuring RCS to use RS internal service address for backoffice API queries

- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/services/ConsentService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/exception/RcsErrorService.java
The previous error message was leaking the client_id of the TPP that owns the consent.
TPPs should have no knowledge of other TPP client_ids.
Cleaning up error message and logging for consent does not exist case.
Fixing bug in redirect uri; adding missing param separator.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/823
> 823: Fixing error message when TPP is fetching a consent that it does not own

- README.md
- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/configuration/ConsentRepoConfiguration.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/configuration/ConsentRepoConfigurationTest.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/resources/application-test.yml
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/configuration/RsBackofficeConfiguration.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/configuration/RsConfiguration.java
- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rcs-server/src/test/resources/application-test.yml
Connection URIs for Consent Repo and RS API are now supplied via the platform config.
Switching to supply the base URI for the API, which removes any assumptions about using k8s internal services (which the previous spring config was doing).
https://github.com/SecureApiGateway/SecureApiGateway/issues/749
> 749: Supplying Consent Repo and RS API URIs via platform config

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/configuration/ApiProviderConfigurationTest.java
Moved the deployment specific config template to the top of the config file as it is the most important thing that the customer needs to be aware of.
Renaming default API provider name to "Test Bank" in order to avoid it being FR specific.
Removing unused spring.application.name config
https://github.com/SecureApiGateway/SecureApiGateway/issues/749
> 749: Moving deployment specific config template to the top of the config file

- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/dto/consent/details/FilePaymentConsentDetails.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/FilePaymentConsentDetailsFactory.java
The RCS UI codebase is expecting a filePayment field in the details response. Reverting the initiation field name back to filePayment.
The UI code has a single object modelling all consent details, therefore we cannot use the initiation field for file data as it does not match the initiation schema of the other payments.
In the future we may want to consider modelling the different consent types in the UI, rather than having a single type: ApiResponses.ConsentDetailsResponse
https://github.com/SecureApiGateway/SecureApiGateway/issues/915
> 915: Renaming FilePaymentConsentDetails initiation field to filePayment

- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/DomesticPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/DomesticScheduledPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/DomesticStandingOrderConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/DomesticVrpPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/InternationalPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/InternationalScheduledPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/InternationalStandingOrderConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/decoder/FRAccountIdentifierDecoder.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/decoder/GsonDecoder.java
- secure-api-gateway-ob-uk-rcs-api/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/ConsentDetailsFactoryProviderTest.java
- secure-api-gateway-ob-uk-rcs-api/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/ConsentDetailsFactoryTest.java
- secure-api-gateway-ob-uk-rcs-api/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/decoder/FRAccountIdentifierDecoderTest.java
This resolves an issue in the UI where the creditor name is not being displayed due to the creditorAccount object being missing.
https://github.com/SecureApiGateway/SecureApiGateway/issues/925
> 925: Adding creditorAccount to payment details initiation objects

- pom.xml
Which uses v2.14.2 of jackson
Issue: SecureApiGateway/SecureApiGateway#929
> 929: Use 0.9.1-SNAPSHOT of parent and bom

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
Address a dependabot version issue
Issue: https://github.com/secureapigateway/secureapigateway/issues/929
> 929: Use 2.8.9 of the gson library

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- Updated deployment descriptor configmapref to use 'deployment-config'
- Updated chart descriptor to update deployment name to 'remote-consent-service'
Issue: https://github.com/secureapigateway/secureapigateway/issues/851
> Upgrade deployment service name and configmap ref

- pom.xml
Update to use 0.9.1 of parent and bom
Issue: https://github.com/secureapigateway/secureapigateway/issues/932
> 932: Prepare for 0.9.1 release

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- Updated pr workflow to pass the variable 'ARGO_VALUES_PREFIX=remoteConsentServer'ilityBank'
- Updated merge master workflow to pass the variable 'ARGO_VALUES_PREFIX=remoteConsentServer'
Issue: https://github.com/secureapigateway/secureapigateway/issues/934
> 934 fix argocd application values prefix on PR pushes to an environment

- pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/models/ConsentClientDecisionRequest.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/test/support/ConsentDecisionRequestTestDataFactory.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDecisionApiController.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDecisionApiControllerTest.java
- Added accountId field in the request object to patch the consent, used in RS when the debtor account in the initiation object It's validated
- The accountId will be the debtor account if has been provided in the consent, otherwise will be the account chosen by the user in the consent decision. 
- Test coverage improvements Issue: https://github.com/secureapigateway/secureapigateway/issues/947
> 947: added logic to store the accounId in the consent and skip patch the debtor account in the consent

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- Helm Charts version updated to 1.0.1 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/969
> 969: Update helm chart to build the release 1.0.1

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- Updated helm chart to 1.0.2
- Bumped commons version 1.0.4
Issue: https://github.com/secureapigateway/secureapigateway/issues/995
> 995: prepare release 1.0.2

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/ConsentStoreEnabledIntentTypesTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DefaultDomesticPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDetailsApiController.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentStoreDecisionService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentStoreDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDecisionApiControllerIdmConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDetailsApiControllerIdmConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentDetailsApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentStoreDecisionServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/ConsentStoreDetailsServiceTest.java
Adding JUnit assumptions to existing Details and Decision controller tests to only run if the particular IntentType is using the old IDM store.
Adding new test classes to test the same controllers when configured to use the RCS Consent Store.
Also improving coverage missed in previous PR.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1010
> 1010: Improving unit test coverage and testing based on consent store configuration

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
Configuring the properties via environment variables supplied from a secret. The properties configure the database, username and password to use in the MongoDB connection string.
Note: we have a convention of using the same database name and username, hence both env vars using the same key.
https://github.com/SecureApiGateway/SecureApiGateway/issues/993
> 993: Configuring Spring Data MongoDB properties

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/v3_1_10/DomesticPaymentConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/v3_1_10/DomesticPaymentConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/v3_1_10/DomesticPaymentConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/domestic/v3_1_10/DomesticPaymentConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/BaseConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domestic/v3_1_10/CreateDomesticPaymentConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/domestic/v3_1_10/DomesticPaymentConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/BaseConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/payment/DomesticPaymentConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/DomesticPaymentConsentRepositoryTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/BaseConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/account/DefaultAccountAccessConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/DefaultDomesticPaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/DomesticPaymentConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/DomesticPaymentConsentDetailsServiceTest.java
Decision has been made to store the FR data model representation because OBIE introduce breaking changes often in their minor API upgrades. Using the FR data model allows us to lessen the impact of some of these issues by applying workarounds in the conversion layer.
For payments, we also store the charges (which get added to the consent response) as the FR data model representation.
Removing the requestType field from the Entity definition, as it is now redundant.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1023
> 1023: Changing Consent Entity definition to store the FR data model representation of a Consent Request

- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/dto/consent/details/DomesticVrpPaymentConsentDetails.java
- secure-api-gateway-ob-uk-rcs-api/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/api/factory/details/DomesticVrpPaymentConsentDetailsFactory.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/DomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/RestDomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/DomesticVRPConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/vrp/v3_1_10/CreateDomesticVRPConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/datamodel/payment/vrp/v3_1_10/DomesticVRPConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/payment/vrp/DomesticVRPConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/payment/vrp/DomesticVRPConsentRepository.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/DefaultDomesticVRPConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/DomesticVRPConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/DefaultDomesticVRPConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/vrp/DomesticVRPConsentDecisionService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/ConsentDetailsApiController.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/vrp/DomesticVRPConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/payment/vrp/DomesticVRPConsentDecisionServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/ConsentDetailsApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/vrp/DomesticVRPConsentDetailsServiceTest.java
Added DomesticVRPConsentEntity to the MongoDB repository, plus support in the service layer and public API.
Implemented details and decision controller logic for this payment type.
Changing the DomesticVrpPaymentConsentDetails to use the FR data model types (rather than OB), and removed the unused readRefundAccount field
https://github.com/SecureApiGateway/SecureApiGateway/issues/1032
> 1032: Adding Support for File Payment Consents to RCS Consent Store

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/account/v3_1_10/AccountAccessConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/PaymentConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/file/v3_1_10/FilePaymentConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/BaseConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/file/DefaultFilePaymentConsentServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentDecisionApiController.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentDecisionApiControllerIdmConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentDecisionApiControllerRcsConsentStoreTest.java
Adding tests for the ConsentDecisionApiController when it is using the RCS Consent Store.
Fixing test assertions to use lessThanOrEqualTo when comparing status updated time, as we only have millisecond precision then sometimes tests fail when they execute quickly with the updated time matching the current time.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1032
> 1032: ConsentDecisionApiController tests with the RCS Consent Store

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- Updated helm charts version to 1.0.3
- Bumped common version 1.0.5
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1040
> 1040: prepare versions to build release 1.0.3

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
Turning on the RCS Consent Store for Domestic Payments
Required as part of RS PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/200
https://github.com/SecureApiGateway/SecureApiGateway/issues/1012
> 1012: Enabling Domestic Payment Consents to use the Consent Store

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/vrp/v3_1_10/DomesticVRPConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/DomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/RestDomesticVRPConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/conent/store/client/payment/vrp/v3_1_10/DomesticVRPConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/payment/vrp/DefaultDomesticVRPConsentServiceTest.java
Domestic VRP Consents are long-lived and support delete (revoking) consent.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1050
> 1050: Adding support for deleting Domestic VRP Consents

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentApiControllerTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/api/funds/v3_1_10/FundsConfirmationConsentValidationHelpers.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/funds/v3_1_10/FundsConfirmationConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/funds/v3_1_10/RestFundsConfirmationConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/funds/v3_1_10/FundsConfirmationConsentStoreClientTest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/datamodel/funds/v3_1_10/AuthoriseFundsConfirmationConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/datamodel/funds/v3_1_10/CreateFundsConfirmationConsentRequest.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/datamodel/funds/v3_1_10/FundsConfirmationConsent.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/entity/funds/FundsConfirmationConsentEntity.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/mongo/funds/FundsConfirmationConsentRepository.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/funds/DefaultFundsConfirmationAccessConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/funds/FundsConfirmationAuthoriseConsentArgs.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/funds/FundsConfirmationConsentService.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/funds/FundsConfirmationConsentStateModel.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/service/funds/DefaultFundsConfirmationAccessConsentServiceTest.java
- Added funds confirmation consent store API, services and  and test coverage
- Added funds confirmation consent store client and test coverage
- Added funds confirmation consent, entity, dto, mongo repositories, sevices and test coverage
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1084
> 1084: funds confirmation store API

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Upgrade version to 2.0.0
- Bumped parent version 2.0.0
- Bumped commons version 2.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099
> 1099: Upgrade version to 2.0.0 Blur release

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- Upgrade helm chart to 2.0.1
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1102
> 1102: prepare release 2.0.1 with helm chart version aligned with pom versions

- _infra/helm/securebanking-openbanking-uk-rcs/templates/deployment.yaml
- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/configuration/CloudClientConfiguration.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/services/ApiClientServiceClient.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/services/UserServiceClient.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/configuration/CloudClientConfigurationTest.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/cloud/client/services/BaseServiceClientTest.java
- secure-api-gateway-ob-uk-rcs-cloud-client/src/test/resources/application-test.yml
- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
- secure-api-gateway-ob-uk-rcs-server/src/test/resources/application-test.yml
CloudClientConfiguration is responsible for configuring the rcs-cloud-client module.
Renamed Spring config properties to use the `cloud.client` prefix
Updated helm chart to set the `cloud.client.baseUri` property to `GATEWAY_DATA_REPO_URI` from the configmap
https://github.com/SecureApiGateway/SecureApiGateway/issues/1082
> 1082: Renaming ConsentRepoConfiguration to CloudClientConfiguration

- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/customerinfo/CustomerInfoConsentDecisionService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/decision/ConsentStoreDecisionServiceRegistryTest.java
- Added annotation @Component in CustomerInfoConsentDecisionService to be bound by Spring
- Added unit test for customer info decision service in the registry tests
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1127
> 1127: customer info decision fix

- pom.xml
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/domestic/DomesticStandingOrderConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/international/InternationalStandingOrderConsentDetailsService.java
- Bumped last commons development version
- Fixed consent details initiation.frequency to display a readable value in RCS UI
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1026
> 1026: standing order details fix

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/repo/exception/ConsentStoreException.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/ConsentDetailsApiController.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/funds/FundsConfirmationConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/BasePaymentConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/ConsentDetailsApiControllerRcsConsentStoreTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/funds/FundsConfirmationConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/domestic/DomesticPaymentConsentDetailsServiceTest.java
Adding ErrorType.INVALID_DEBTOR_ACCOUNT error code for this case. Updating the details controller to handle this error and produce a suitable error redirect_uri.
Example redirect_uri:
```
https://postman-echo.com/get#error=access_denied&state=10d260bf-a7d9-444a-92d9-7b7a5f088208&error_description=%20User%20is%20not%20permissioned%20to%20make%20a%20payment%20from%20the%20debtorAccount%20specified&error_uri=https://tools.ietf.org/html/rfc6749%23section-4.1.2.1
```
https://github.com/SecureApiGateway/SecureApiGateway/issues/1131
> 1131: Improving error message when the user does not own the debtorAccount specified in the consent

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Updated helm chart version to 2.1.0
- Updated development version to 2.1.0-SNAPSHOT
- Bumped commons version 2.1.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1148
> 1148: prepare release 2.1.0

- pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/configuration/RcsApplicationConfiguration.java
- secure-api-gateway-ob-uk-rcs-server/src/main/resources/logback.xml
- secure-api-gateway-ob-uk-rcs-server/src/test/resources/logback-test.xml
FapiInteractionIdFilter stores the x-fapi-interaction-id in the MDC log context
Updating logging configuration to use a JSON log format, which automatically adds the MDC data to the log message. Logging is now consistent with IG.
Adding logback dependencies to support JSON logging.
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Installing FapiInteractionIdFilter in order to trace requests through the system

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/client/BaseRestConsentStoreClient.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/src/test/java/com/forgerock/sapi/gateway/rcs/consent/store/client/BaseRestConsentStoreClientTest.java
Updating BaseRestConsentStoreClient to set the x-fapi-interaction-id header in requests. The value is sourced from the FapiInteractionIdContext, or randomly generated if this is null.
Note: requires: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-common/pull/142 to be merged before this will compile.
https://github.com/SecureApiGateway/SecureApiGateway/issues/863
> 863: Pass x-fapi-interaction-id in calls to Consent Store API

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Updated helm chart to 2.2.0
- bumped commons 2.2.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182
> Prepare release 2.2.0

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- secure-api-gateway-ob-uk-rcs-server/docker/docker-compose-git.yml
- secure-api-gateway-ob-uk-rcs-server/docker/docker-compose.yml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202
> 987: Artifact Registry Migration

- secure-api-gateway-ob-uk-rcs-server/pom.xml
Switching to jdk18on (JDK 1.8+) flavour of bouncy castle libraries as version 1.77 is only available for this artifactId.
See PR: https://github.com/SecureApiGateway/secure-api-gateway-parent/pull/87
https://github.com/SecureApiGateway/SecureApiGateway/issues/1223
> 1223: Updating to bouncy castle version 1.77

- secure-api-gateway-ob-uk-rcs-server/src/main/resources/application.yml
server.max-http-header-size has been deprecated and has been replaced with server.max-http-request-header-size, updating our application config to use the new property
https://github.com/SecureApiGateway/SecureApiGateway/issues/1235
> 1235: Configure server.max-http-request-header-size

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Bump parent and bom to 2.3.0
Bump helm charts to 2.3.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Prepare release 2.3.0

- .github/workflows/release.yml
- Makefile
- secure-api-gateway-ob-uk-rcs-server/pom.xml
We were only passing the sbat-gcr-develop as ${gcrRepo} and overwriting it with sbat-gcr-release when doing a release, but the value of GAR_RELEASE_REPO contains the full GAR url of europe-west4-docker.pkg.dev/sbat-gcr-release/sapig-docker-artifact
So modifying the existing values so that the end value is valid
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
> 1251: Fix release workflows

- pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
These dependencies are no longer being used.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1267
> 1267: Removing mockito-inline and gson dependencies

- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/funds/FundsConfirmationConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/BasePaymentConsentDetailsService.java
- secure-api-gateway-ob-uk-rcs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/client/rs/AccountService.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/funds/FundsConfirmationConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/BasePaymentConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/domestic/DomesticScheduledPaymentConsentDetailsServiceTest.java
- secure-api-gateway-ob-uk-rcs-server/src/test/java/com/forgerock/sapi/gateway/ob/uk/rcs/server/api/details/payment/domestic/DomesticStandingOrderConsentDetailsServiceTest.java
Latest RS backoffice API has removed the name param and made the userId param mandatory. Currently, the RCS always supplies the userId, cleaning up the code to stop sending the name param (which would be ignored).
https://github.com/SecureApiGateway/SecureApiGateway/issues/1479
> 1479: Remove unused name param from findByAccountIdentifiers query

- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/BaseDomesticPaymentConsentApiController.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/DomesticPaymentConsentApi.java
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/src/main/java/com/forgerock/sapi/gateway/rcs/consent/store/api/payment/domestic/v3_1_10/DomesticPaymentConsentApiController.java
Refactoring the DomesticPaymentConsentApi, removing the class level RequestMapping annotation from the interface and instead supplying it in the version specific controller impl.
Extracting BaseDomesticPaymentConsentApiController from DomesticPaymentConsentApiController, this class contains the common controller logic that is the same across versions. Version specific controllers extend the Base and supply the OBVersion parameter as well as the annotations to wire the controller in Spring and to specify the RequestMapping (as the URL pattern is version specific).
The same pattern will be followed for all Consent API controllers.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1440
> 1440: Allow Consent API controllers to be configured for specific OB versions

- _infra/helm/securebanking-openbanking-uk-rcs/Chart.yaml
- pom.xml
Bump `Parent`, `Common` and `helm`
Same issue as Common, removed the ${revision} to get the release done
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
> 1602: Build and Deploy SAPIG 4.0.0

- .gitignore
- pom.xml
- Reorder pom.xml to align with outputted pom.xml after running flatten:flatten command
- Use resolveCiFriendliesOnly instead of bom
- Add files to .gitignore
When testing locally, got further than before with current format
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1606
> 1606: Investigate issues with release when using flatten commands

- pom.xml
- secure-api-gateway-ob-uk-rcs-api/pom.xml
- secure-api-gateway-ob-uk-rcs-cloud-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-api/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-client/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-datamodel/pom.xml
- secure-api-gateway-ob-uk-rcs-consent-store/secure-api-gateway-ob-uk-rcs-consent-store-repo/pom.xml
- secure-api-gateway-ob-uk-rcs-server/pom.xml
- Remove `${revision}` for `5.0.3-SNAPSHOT` ready for release
- Revert parent and common to `5.0.0`
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322?selectedIssue=OPENIG-9650
> OpenIG-9650: SAPIG 5.0.3 Release
